services:
  - type: web
    name: support-bot
    env: python
    region: frankfurt  # или oregon, если ближе к вам
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: jeknes
        sync: false
